version: '3.9'

volumes:
  auth_db_data: null
  storage_db_data: null
  redis_data: null
  temp_file_storage: null
  s1_1_data: null
  s1_2_data: null
  s1_3_data: null
  s2_1_data: null
  s3_1_data: null

services:
  auth_db:
    image: postgres:14.5-alpine
    volumes:
      - auth_db_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=${AUTH_DB__USER}
      - POSTGRES_PASSWORD=${AUTH_DB__PASSWORD}
      - POSTGRES_DB=${AUTH_DB__DBNAME}
    ports:
      - "${AUTH_DB__PORT}:${AUTH_DB__PORT}"
    command: -p ${AUTH_DB__PORT}

  storage_db:
    image: postgres:14.5-alpine
    volumes:
      - storage_db_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=${STORAGE_DB__USER}
      - POSTGRES_PASSWORD=${STORAGE_DB__PASSWORD}
      - POSTGRES_DB=${STORAGE_DB__DBNAME}
    ports:
      - "${STORAGE_DB__PORT}:${STORAGE_DB__PORT}"
    command: -p ${STORAGE_DB__PORT}

  nginx:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth
      - storage
    ports:
      - "80:80"
    restart: always

  redis:
    image: redis:7.0.5-alpine
    volumes:
      - redis_data:/var/lib/redis
    restart: always
    ports:
      - "${CACHE__PORT}:${CACHE__PORT}"

  rabbit:
    image: rabbitmq:3.10-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ__USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ__PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ__VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build: auth
    depends_on:
      - auth_db
      - redis
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
  
  storage:
    build: storage
    volumes:
      - temp_file_storage:/temp_storage/
    depends_on:
      - storage_db
      - redis
      - rabbit
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - .env
    command: ["gunicorn", "src.entrypoints.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8002", "--forwarded-allow-ips", "*"]

  worker_event_listener:
    build: storage
    volumes:
      - temp_file_storage:/temp_storage/
    depends_on:
      - storage_db
      - redis
      - rabbit
    restart: always
    env_file:
      - .env
    command: ["python", "src/entrypoints/event_listener.py"]

  worker_file_operator:
    build: storage
    volumes:
      - temp_file_storage:/temp_storage/
    depends_on:
      - storage_db
      - redis
      - rabbit
    restart: always
    env_file:
      - .env
    command: ["python", "src/entrypoints/file_operator.py"]

  s1_1:
    image: 'quay.io/minio/minio:latest'
    ports:
      - '9001:9000'
      - '9091:9090'
    depends_on:
      - rabbit
    volumes:
      - s1_1_data:/data/
    environment:
      - MINIO_ROOT_USER=${S3__USER}
      - MINIO_ROOT_PASSWORD=${S3__PASSWORD}
      - MINIO_NOTIFY_AMQP_ENABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_URL_RABBIT=amqp://${RABBITMQ__USER}:${RABBITMQ__PASSWORD}@${RABBITMQ__HOST}:${RABBITMQ__PORT}/${RABBITMQ__VHOST}
      - MINIO_NOTIFY_AMQP_EXCHANGE_RABBIT=${RABBITMQ__EXCHANGE}
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_RABBIT=topic
      - MINIO_NOTIFY_AMQP_ROUTING_KEY_RABBIT=S3.s1_1.EVENT
      - MINIO_NOTIFY_AMQP_DURABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_MANDATORY_RABBIT=on
      - MINIO_NOTIFY_AMQP_DELIVERY_MODE_RABBIT=2
    env_file:
      - .env
    command: server /data --console-address ":9090"

  s1_2:
    image: 'quay.io/minio/minio:latest'
    ports:
      - '9002:9000'
      - '9092:9090'
    depends_on:
      - rabbit
    volumes:
      - s1_2_data:/data/
    environment:
      - MINIO_ROOT_USER=${S3__USER}
      - MINIO_ROOT_PASSWORD=${S3__PASSWORD}
      - MINIO_NOTIFY_AMQP_ENABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_URL_RABBIT=amqp://${RABBITMQ__USER}:${RABBITMQ__PASSWORD}@${RABBITMQ__HOST}:${RABBITMQ__PORT}/${RABBITMQ__VHOST}
      - MINIO_NOTIFY_AMQP_EXCHANGE_RABBIT=${RABBITMQ__EXCHANGE}
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_RABBIT=topic
      - MINIO_NOTIFY_AMQP_ROUTING_KEY_RABBIT=S3.s1_2.EVENT
      - MINIO_NOTIFY_AMQP_DURABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_MANDATORY_RABBIT=on
      - MINIO_NOTIFY_AMQP_DELIVERY_MODE_RABBIT=2
    env_file:
      - .env
    command: server /data --console-address ":9090"

  s1_3:
    image: 'quay.io/minio/minio:latest'
    ports:
      - '9003:9000'
      - '9093:9090'
    depends_on:
      - rabbit
    volumes:
      - s1_3_data:/data/
    environment:
      - MINIO_ROOT_USER=${S3__USER}
      - MINIO_ROOT_PASSWORD=${S3__PASSWORD}
      - MINIO_NOTIFY_AMQP_ENABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_URL_RABBIT=amqp://${RABBITMQ__USER}:${RABBITMQ__PASSWORD}@${RABBITMQ__HOST}:${RABBITMQ__PORT}/${RABBITMQ__VHOST}
      - MINIO_NOTIFY_AMQP_EXCHANGE_RABBIT=${RABBITMQ__EXCHANGE}
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_RABBIT=topic
      - MINIO_NOTIFY_AMQP_ROUTING_KEY_RABBIT=S3.s1_3.EVENT
      - MINIO_NOTIFY_AMQP_DURABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_MANDATORY_RABBIT=on
      - MINIO_NOTIFY_AMQP_DELIVERY_MODE_RABBIT=2
    env_file:
      - .env
    command: server /data --console-address ":9090"

  s2_1:
    image: 'quay.io/minio/minio:latest'
    ports:
      - '9004:9000'
      - '9094:9090'
    depends_on:
      - rabbit
    volumes:
      - s2_1_data:/data/
    environment:
      - MINIO_ROOT_USER=${S3__USER}
      - MINIO_ROOT_PASSWORD=${S3__PASSWORD}
      - MINIO_NOTIFY_AMQP_ENABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_URL_RABBIT=amqp://${RABBITMQ__USER}:${RABBITMQ__PASSWORD}@${RABBITMQ__HOST}:${RABBITMQ__PORT}/${RABBITMQ__VHOST}
      - MINIO_NOTIFY_AMQP_EXCHANGE_RABBIT=${RABBITMQ__EXCHANGE}
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_RABBIT=topic
      - MINIO_NOTIFY_AMQP_ROUTING_KEY_RABBIT=S3.s2_1.EVENT
      - MINIO_NOTIFY_AMQP_DURABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_MANDATORY_RABBIT=on
      - MINIO_NOTIFY_AMQP_DELIVERY_MODE_RABBIT=2
    env_file:
      - .env
    command: server /data --console-address ":9090"

  s3_1:
    image: 'quay.io/minio/minio:latest'
    ports:
      - '9005:9000'
      - '9095:9090'
    depends_on:
      - rabbit
    volumes:
      - s3_1_data:/data/
    environment:
      - MINIO_ROOT_USER=${S3__USER}
      - MINIO_ROOT_PASSWORD=${S3__PASSWORD}
      - MINIO_NOTIFY_AMQP_ENABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_URL_RABBIT=amqp://${RABBITMQ__USER}:${RABBITMQ__PASSWORD}@${RABBITMQ__HOST}:${RABBITMQ__PORT}/${RABBITMQ__VHOST}
      - MINIO_NOTIFY_AMQP_EXCHANGE_RABBIT=${RABBITMQ__EXCHANGE}
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_RABBIT=topic
      - MINIO_NOTIFY_AMQP_ROUTING_KEY_RABBIT=S3.s3_1.EVENT
      - MINIO_NOTIFY_AMQP_DURABLE_RABBIT=on
      - MINIO_NOTIFY_AMQP_MANDATORY_RABBIT=on
      - MINIO_NOTIFY_AMQP_DELIVERY_MODE_RABBIT=2
    env_file:
      - .env
    command: server /data --console-address ":9090"