version: '3.9'

services:
  # s3:
  #   image: quay.io/minio/minio
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   volumes:
  #     - ${HOME}/minio/data:/data
  #   environment:
  #     - MINIO_ROOT_USER=admin
  #     - MINIO_ROOT_PASSWORD=admin
  #   entrypoint: ["server",  "/data",  "--console-address", ":9090"]
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    volumes:
      - ${HOME}/minio/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3