version: '3.9'

volumes:
  postgres_data: null
  redis_data: null

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env.prod
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DBNAME}
    ports:
      - "5432:5432"

  # flask:
  #   build: flask
  #   depends_on:
  #     - db
  #   restart: always
  #   env_file:
  #     - ./.env.prod
  #   command: ["/bin/bash", "-c", "./entrypoint.sh && uwsgi --strict --ini uwsgi.ini"]

  # nginx:
  #   image: nginx:1.23.1
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - flask
  #     - fastapi
  #   ports:
  #     - "80:80"
  #   restart: always

  # redis:
  #   image: redis:7.0.5-alpine
  #   volumes:
  #     - redis_data:/var/lib/redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  # fastapi:
  #   build: fastapi
  #   depends_on:
  #     - flask
  #   restart: always
  #   env_file:
  #     - ./.env.prod

  # jaeger:
  #   image: jaegertracing/all-in-one:1.39.0
  #   ports:
  #     - "16686:16686"
  #   restart: always
