@startuml

package "Client (frontend)" as client {}

package "Auth Service" as auth {}
package "Auth DB" as auth_db {}

package "Storage Service" as storage {}
package "Storage DB" as storage_db {}

package "GeoIP Service" as geo {
  note "Получение данных по IP" as N1
}

together {
package "RabbitMQ" as rabbit {
  rabbit.Exchange : STORAGE

  rabbit.Queue : LISTEN_S3_EVENTS
  rabbit.Queue : FILE OPERATIONS
}

package "Redis" as redis {
    note "Идемпотентность" as N2
}

package "S3 Servers" as s3 {
    object s3.Server
    s3.Server : Server1
    s3.Server : Server2
    s3.Server : Server3
}

package "S3 Events Worker" as s3_worker {
  note "Обработка событий S3" as N3
}

package "File Operations Worker" as file_worker {
  note "Операциии с файлами" as N4
}

}

client --> auth
client --> storage
storage --> auth

auth <--> auth_db
storage <--> storage_db
file_worker <--> storage_db
s3_worker <--> storage_db
storage <-- geo

s3 --> rabbit
storage <--> rabbit
s3_worker <--> rabbit
file_worker <--> rabbit

auth <--> redis
storage <--> redis
s3_worker <--> redis
file_worker <--> redis

@enduml