const Single = {
  type: "object",
  properties: {
    name: {
      type: "string",
      enum: [
        "can_get_folders",
        "can_view_settings",
        "can_view_folder",
        "can_add_folder",
        "can_change_folder",
        "can_delete_folder",
        "can_view_user",
        "can_change_user",
        "can_delete_user",
        "can_view_role",
        "can_view_permission",
        "can_change_permission",
        "can_add_role",
        "can_change_role",
        "can_delete_role",
        "can_view_document",
        "can_add_document",
        "can_change_document",
        "can_delete_document",
        "can_view_file",
        "can_add_file",
        "can_change_file",
        "can_delete_file",
        "can_view_userfoldersetting",
        "can_add_userfoldersetting",
        "can_change_userfoldersetting",
        "can_delete_userfoldersetting",
        "can_view_usergroup",
        "can_add_usergroup",
        "can_change_usergroup",
        "can_delete_usergroup",
        "can_view_service",
        "can_view_flow",
        "can_add_flow",
        "can_change_flow",
        "can_delete_flow",
        "can_view_flowitem",
        "can_add_flowitem",
        "can_change_flowitem",
        "can_delete_flowitem",
        "can_view_flowitemstep",
        "can_view_documentapproval",
        "can_add_documentapproval",
        "can_change_documentapproval",
        "can_delete_documentapproval",
        "can_delegate_documentapproval",
        "can_search_documentapproval",
        "can_empty_cart",
        "can_view_cart",
        "can_add_to_cart",
        "can_remove_from_cart",
        "can_view_userreplacement",
        "can_add_userreplacement",
        "can_delete_userreplacement",
        "can_view_onbehalfuser",
        "can_change_onbehalfuser",
        "can_delete_onbehalfuser",
        "can_view_documentapprovalflow",
        "can_change_documentapprovalflow",
        "can_delete_documentapprovalflow",
        "can_view_serversetting",
        "can_change_serversetting",
        "can_view_mailbox",
        "can_add_mailbox",
        "can_change_mailbox",
        "can_delete_mailbox",
        "can_view_mailchannel",
        "can_add_mailchannel",
        "can_change_mailchannel",
        "can_delete_mailchannel",
        "can_fetch_mailchannel",
        "can_view_mail",
        "can_delete_mail",
        "can_view_counter",
        "can_add_counter",
        "can_change_counter",
        "can_delete_counter",
        "can_fetch_counter",
        "can_view_xmldocument",
        "can_add_xmldocument",
        "can_change_xmldocument",
        "can_delete_xmldocument",
        "can_view_alluserreplacement",
        "can_add_alluserreplacement",
        "can_delete_alluserreplacement",
        "can_view_transmittal"
      ],
    },
    is_for_folder: {
      type: "boolean",
    },
  },
  required: ["name", "is_for_folder"],
};

const List = {
  type: "array",
  items: Single,
};

export { Single, List };
