CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE servers
(
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    host VARCHAR(15) NOT NULL,
    port INTEGER NOT NULL,
    location VARCHAR(100),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);